// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQtzkLnyVEQ48Q9_7qtjvgkkPFq2OFq3U',
    appId: '1:141233285447:web:ea2a19bea4807247a54462',
    messagingSenderId: '141233285447',
    projectId: 'spotifyflclone',
    authDomain: 'spotifyflclone.firebaseapp.com',
    storageBucket: 'spotifyflclone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyyBwVfsDe3kqt5q3Ad7reNXx3PBMLn64',
    appId: '1:141233285447:android:0bf7901e39318f99a54462',
    messagingSenderId: '141233285447',
    projectId: 'spotifyflclone',
    storageBucket: 'spotifyflclone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSdawi6UutoeWdqKoKv0E68AoRKQzAYeQ',
    appId: '1:141233285447:ios:b48ad7b65c9ab6d8a54462',
    messagingSenderId: '141233285447',
    projectId: 'spotifyflclone',
    storageBucket: 'spotifyflclone.appspot.com',
    iosBundleId: 'com.example.spotifyflutterclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSdawi6UutoeWdqKoKv0E68AoRKQzAYeQ',
    appId: '1:141233285447:ios:b48ad7b65c9ab6d8a54462',
    messagingSenderId: '141233285447',
    projectId: 'spotifyflclone',
    storageBucket: 'spotifyflclone.appspot.com',
    iosBundleId: 'com.example.spotifyflutterclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQtzkLnyVEQ48Q9_7qtjvgkkPFq2OFq3U',
    appId: '1:141233285447:web:075284cba8ac9776a54462',
    messagingSenderId: '141233285447',
    projectId: 'spotifyflclone',
    authDomain: 'spotifyflclone.firebaseapp.com',
    storageBucket: 'spotifyflclone.appspot.com',
  );
}
